### ISSUE TITLE
Task creation is not possible 

### ISSUE THREAD

**Issue by souibguimohamed** [hsk-kr/linkedin-job-scanner#1] opened 2024-05-13 16:53 UTC
I try to use the extension, but unfortunately, when I fill out the form and click on "create" to create a new task, it fails to function.

**Comment by hsk-kr** [comment] 2024-05-13 17:06
I'm sorry for the inconvenience and thank you so much for reporting the error.

I reinstalled the plugin [here](https://chromewebstore.google.com/detail/job-scanner/jpfldhdekpcpihghnbhigmjmdcemgkhi?hl=en-US&utm_source=ext_sidebar) and found the feature still worked.

If you don't mind, could you give me more information like pictures or the versions of your chrome and the extension?
Is there any error message in the input fields?

**Comment by hsk-kr** [comment] 2024-05-14 18:08
I've encountered the same issue, it's caused by storing more than it can store in the storage, it may work after deleting other tasks to make more space. I will work on the new version of the extension and this issue will be solved but in the new version, you may reinstall the chrome extension to make it work. Thank you!

**Comment by hsk-kr** [comment] 2024-05-22 10:03
The new version is released. I believe the task might be solved in the new version.

**Comment by hsk-kr** [comment] 2024-05-25 19:05
I will be closing the issue. If you still encounter the problem, please open the issue again.

**Closed by hsk-kr** 2024-05-25 19:05 UTC
